// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy0paV1ScPQfcZRIuRQIbuwduFj0xlJIc',
    appId: '1:517208651594:web:d978e453ada966e1d2f3b3',
    messagingSenderId: '517208651594',
    projectId: 'test-3ded8',
    authDomain: 'test-3ded8.firebaseapp.com',
    storageBucket: 'test-3ded8.appspot.com',
    measurementId: 'G-D42CWTXGK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0fl_bjrxPEv-2pgKWJsZMb6n-pDr6wiU',
    appId: '1:517208651594:android:156ca5de2824e29cd2f3b3',
    messagingSenderId: '517208651594',
    projectId: 'test-3ded8',
    storageBucket: 'test-3ded8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSYzAF5XpJUwuONZPDimCs_V-SOmA4vCU',
    appId: '1:517208651594:ios:110c2729ebb5b74dd2f3b3',
    messagingSenderId: '517208651594',
    projectId: 'test-3ded8',
    storageBucket: 'test-3ded8.appspot.com',
    iosBundleId: 'com.example.formtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSYzAF5XpJUwuONZPDimCs_V-SOmA4vCU',
    appId: '1:517208651594:ios:110c2729ebb5b74dd2f3b3',
    messagingSenderId: '517208651594',
    projectId: 'test-3ded8',
    storageBucket: 'test-3ded8.appspot.com',
    iosBundleId: 'com.example.formtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy0paV1ScPQfcZRIuRQIbuwduFj0xlJIc',
    appId: '1:517208651594:web:40a20c24d89afddbd2f3b3',
    messagingSenderId: '517208651594',
    projectId: 'test-3ded8',
    authDomain: 'test-3ded8.firebaseapp.com',
    storageBucket: 'test-3ded8.appspot.com',
    measurementId: 'G-10EM03EP4G',
  );
}
